<a href="https://colab.research.google.com/github/prithviratkalkar2304-coder/Prithvi_Ratkalkar/blob/main/Data%20Binning%20/Experiment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 13
##Title: Data Binning and Formatting
##20 March 2026
##Prithvi Ratkalkar
##PRN: 25070123165
##ENTC A1

In [3]:
import pandas as pd
import numpy as np

Dataset = {
    "Student" : ["A","B","C","D","E","F"],
    "Marks" : [99,88,77,66,87,98],
    "Attendance" : [75,90,23,78,67,100],
    "Grade" : ["A","B","C","D","B","A"]
}
df = pd.DataFrame(Dataset)
print(df)

  Student  Marks  Attendance Grade
0       A     99          75     A
1       B     88          90     B
2       C     77          23     C
3       D     66          78     D
4       E     87          67     B
5       F     98         100     A

In [4]:
# Data Binning
Range = [60,70,80,90,100]
Category = ["Below Avg","Average","Above Avg","Top"]
df["Grade"] = pd.cut(df["Marks"],bins=Range,labels=Category)
print(df)

  Student  Marks  Attendance      Grade
0       A     99          75        Top
1       B     88          90  Above Avg
2       C     77          23    Average
3       D     66          78  Below Avg
4       E     87          67  Above Avg
5       F     98         100        Top

In [5]:
# Binning the attendance of students
New_Range = [0,25,50,74,100]
New_Category = ["Too Low","Low","Conserning","Safe"]
df["Attendance"] = (pd.cut(df["Attendance"],bins=New_Range,labels=New_Category))
print(df)

  Student  Marks  Attendance      Grade
0       A     99        Safe        Top
1       B     88        Safe  Above Avg
2       C     77     Too Low    Average
3       D     66        Safe  Below Avg
4       E     87  Conserning  Above Avg
5       F     98        Safe        Top

In [6]:
# Data formatting
# Coversion of data type
Dataset = {
    "Student" : ["A","B","C","D","E","F"],
    "Marks" : [99,88,77,66,87,98],
    "Attendance" : [75,90,23,78,67,100],
    "Grade" : ["A","B","C","D","B","A"]
}
df = pd.DataFrame(Dataset)
print(df)

  Student  Marks  Attendance Grade
0       A     99          75     A
1       B     88          90     B
2       C     77          23     C
3       D     66          78     D
4       E     87          67     B
5       F     98         100     A

In [7]:
print(df.dtypes)
df["Attendance"] = df["Attendance"].astype(float)
print(df)

Student       object
Marks          int64
Attendance     int64
Grade         object
dtype: object
  Student  Marks  Attendance Grade
0       A     99        75.0     A
1       B     88        90.0     B
2       C     77        23.0     C
3       D     66        78.0     D
4       E     87        67.0     B
5       F     98       100.0     A

In [8]:
# Rounding Values Of Attendance
df["Attendance"] = df["Attendance"].round(2)
print(df)

  Student  Marks  Attendance Grade
0       A     99        75.0     A
1       B     88        90.0     B
2       C     77        23.0     C
3       D     66        78.0     D
4       E     87        67.0     B
5       F     98       100.0     A

In [9]:
# Additional Operations
# Sorting data
sorted_df = df.sort_values(by="Marks")
print(sorted_df)

  Student  Marks  Attendance Grade
3       D     66        78.0     D
2       C     77        23.0     C
4       E     87        67.0     B
1       B     88        90.0     B
5       F     98       100.0     A
0       A     99        75.0     A

In [10]:
 #Displaying Unique Values
print(df["Attendance"].unique())

[ 75.  90.  23.  78.  67. 100.]

In [11]:
Fruits = {
    "Fruit" : ["Apple","Banana","Mango","Orange","Grapes"],
    "Price" : [150,60,400,200,70],
    "Calories" :[130,500,270,60,420],
    "Weight" : [100,50,200,60,80]
}

df = pd.DataFrame(Fruits)
print(df)

    Fruit  Price  Calories  Weight
0   Apple    150       130     100
1  Banana     60       500      50
2   Mango    400       270     200
3  Orange    200        60      60
4  Grapes     70       420      80

In [12]:
Range = [0,100,200,400]
Categories = ["Cheap","General","Expensive"]
df["Price"] = pd.cut(df["Price"],bins=Range,labels=Categories)
print(df)

    Fruit      Price  Calories  Weight
0   Apple    General       130     100
1  Banana      Cheap       500      50
2   Mango  Expensive       270     200
3  Orange    General        60      60
4  Grapes      Cheap       420      80

In [13]:
New_Range = [0,100,200,500]
New_Category = ["Low","Medium","High"]
df["Calories"] = pd.cut(df["Calories"],bins=New_Range,labels=New_Category)
print(df)

    Fruit      Price Calories  Weight
0   Apple    General   Medium     100
1  Banana      Cheap     High      50
2   Mango  Expensive     High     200
3  Orange    General      Low      60
4  Grapes      Cheap     High      80

In [14]:
Fruits = {
    "Fruit" : ["Apple","Banana","Mango","Orange","Grapes"],
    "Price" : [150,60,400,200,70],
    "Calories" :[130,500,270,60,420],
    "Weight" : [100,50,200,60,80]
}
df = pd.DataFrame(Fruits)
df["Price"] = df["Price"].astype(float)
df["Fruit"] = df["Fruit"].str.upper()
df

    Fruit  Price  Calories  Weight
0   APPLE  150.0       130     100
1  BANANA   60.0       500      50
2   MANGO  400.0       270     200
3  ORANGE  200.0        60      60
4  GRAPES   70.0       420      80

In [15]:
sorted_df = df.sort_values(by="Price")
sorted_df

    Fruit  Price  Calories  Weight
1  BANANA   60.0       500      50
4  GRAPES   70.0       420      80
0   APPLE  150.0       130     100
3  ORANGE  200.0        60      60
2   MANGO  400.0       270     200

In [16]:
print(df["Weight"].unique())

[100  50 200  60  80]

In [17]:
print(df['Price'].value_counts())

Price
150.0    1
60.0     1
400.0    1
200.0    1
70.0     1
Name: count, dtype: int64