<a href="https://colab.research.google.com/github/prithviratkalkar2304-coder/Prithvi_Ratkalkar/blob/main/Data%20Normalization%20/%20Experiment14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name:Prithvi Ratkalkar

PRN:25070123165

Batch: ENTC-A1


#Experiment-14
#Data Normalization and Data Type Conversion(Part A-Data Normalization)

In [ ]:
#DataSet
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','SmartWatch','Camera'],
    'Price':[55000,20000,30000,45000,5000,120000],
    'Units_Sold':[25,60,23,45,65,8],
    'Discount':[10,20,40,35,16,30]
}
df=pd.DataFrame(data)
print("Original Data:")
print(df)

Original Data:
      Product   Price  Units_Sold  Discount
0      Laptop   55000          25        10
1      Mobile   20000          60        20
2      Tablet   30000          23        40
3  Headphones   45000          45        35
4  SmartWatch    5000          65        16
5      Camera  120000           8        30

In [ ]:
#1 min-max normalization
#min-max normalization for price
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print("\nMin-Max Normalized Price:")
print(df[['Product','Price','Price_MinMax']])

Min-Max Normalized Price:
      Product     Price  Price_MinMax
0      Laptop  0.434783      0.434783
1      Mobile  0.130435      0.130435
2      Tablet  0.217391      0.217391
3  Headphones  0.347826      0.347826
4  SmartWatch  0.000000      0.000000
5      Camera  1.000000      1.000000

In [ ]:
#Normalize Multiple Columns
cols=['Price','Units_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nNormalized Multiple Columns:")
print(df_norm)

Normalized Multiple Columns:
      Price  Units_Sold  Discount
0  0.434783    0.298246  0.000000
1  0.130435    0.912281  0.333333
2  0.217391    0.263158  1.000000
3  0.347826    0.649123  0.833333
4  0.000000    1.000000  0.200000
5  1.000000    0.000000  0.666667

In [ ]:
#2 Z-score normalization
df['Units_Zscore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
print("\nZ-score Normalized Units_Sold:")
print(df[['Product','Units_Sold','Units_Zscore']])

Z-score Normalized Units_Sold:
      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.560304
1      Mobile          60      0.987904
2      Tablet          23     -0.648773
3  Headphones          45      0.324386
4  SmartWatch          65      1.209077
5      Camera           8     -1.312290

In [ ]:
#3 Decimal Scaling
df['Price_Decimal']=df['Price']/1000000
print("\nDecimal Scaled Price:")
print(df[['Product','Price','Price_Decimal']])

Decimal Scaled Price:
      Product   Price  Price_Decimal
0      Laptop   55000          0.055
1      Mobile   20000          0.020
2      Tablet   30000          0.030
3  Headphones   45000          0.045
4  SmartWatch    5000          0.005
5      Camera  120000          0.120

In [ ]:
#New Data Set

import pandas as pd
df=pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')

In [ ]:
#min-max normalization
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print("\nMin-Max Normalized Price:")
print(df[['Product_Name','Price','Price_MinMax']])

Min-Max Normalized Price:
                   Product_Name  Price  Price_MinMax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

In [ ]:
#Normalize Multiple Columns
cols=['Price','Units_Sold','Rating']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nNormalized Multiple Columns:")
print(df_norm)

Normalized Multiple Columns:
       Price  Units_Sold    Rating
0   0.020243    0.518519  0.428571
1   0.048583    0.277778  0.714286
2   0.016194    0.203704  0.142857
3   0.089069    0.629630  0.857143
4   0.149798    0.833333  0.571429
5   0.036437    0.592593  0.285714
6   0.024291    0.129630  0.000000
7   0.064777    0.351852  0.428571
8   0.210526    0.481481  1.000000
9   0.028340    0.222222  0.285714
10  0.311741    1.000000  0.857143
11  0.174089    0.407407  0.714286
12  0.052632    0.500000  0.571429
13  0.016194    0.092593  0.142857
14  0.024291    0.240741  0.285714
15  0.251012    0.444444  0.857143
16  0.036437    0.259259  0.428571
17  0.068826    0.648148  0.571429
18  0.109312    0.851852  0.714286
19  0.040486    0.351852  0.428571
20  0.008097    0.148148  0.000000
21  0.089069    0.444444  0.571429
22  0.352227    0.185185  0.857143
23  0.020243    0.259259  0.285714
24  0.129555    0.592593  0.714286
25  0.174089    0.166667  0.571429
26  0.514170    0.129630  1.000000
27  0.076923    0.370370  0.428571
28  0.016194    0.314815  0.285714
29  0.048583    0.351852  0.428571
30  0.392713    0.240741  0.857143
31  0.230769    0.203704  0.714286
32  0.129555    0.666667  0.571429
33  0.473684    0.092593  0.857143
34  0.635628    0.037037  1.000000
35  0.012146    0.166667  0.142857
36  0.020243    0.462963  0.285714
37  0.000000    0.574074  0.000000
38  0.028340    0.259259  0.428571
39  0.048583    0.111111  0.571429
40  0.109312    0.148148  0.714286
41  0.433198    0.074074  0.857143
42  0.190283    0.351852  0.571429
43  1.000000    0.000000  1.000000
44  0.068826    0.444444  0.428571
45  0.311741    0.240741  0.857143
46  0.757085    0.092593  0.714286
47  0.089069    0.185185  0.571429
48  0.129555    0.148148  0.428571
49  0.028340    0.314815  0.285714

In [ ]:
df['Units_Zscore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
print("\nZ-score Normalized Units_Sold:")
print(df[['Product_Name','Units_Sold','Units_Zscore']])

Z-score Normalized Units_Sold:
                   Product_Name  Units_Sold  Units_Zscore
0                Wireless Mouse         350      0.812282
1             Bluetooth Speaker         220     -0.260855
2                  USB Keyboard         180     -0.591051
3                Gaming Headset         410      1.307576
4                    Smartwatch         520      2.215615
5                    Power Bank         390      1.142478
6                  Laptop Stand         140     -0.921247
7                        Webcam         260      0.069341
8                  Portable SSD         330      0.647184
9              Wireless Charger         190     -0.508502
10  Noise Cancelling Headphones         610      2.958556
11          Mechanical Keyboard         290      0.316988
12                 Gaming Mouse         340      0.729733
13                 Tablet Stand         120     -1.086345
14                      USB Hub         200     -0.425953
15          External Hard Drive         310      0.482086
16            Smartphone Tripod         210     -0.343404
17              Laptop Backpack         420      1.390125
18            Bluetooth Earbuds         530      2.298164
19                LED Desk Lamp         260      0.069341
20                 Phone Holder         150     -0.838698
21            Wireless Keyboard         310      0.482086
22             Portable Monitor         170     -0.673600
23                   Smart Plug         210     -0.343404
24                  WiFi Router         390      1.142478
25              Graphics Tablet         160     -0.756149
26                   VR Headset         140     -0.921247
27                   Microphone         270      0.151890
28             Smart Light Bulb         240     -0.095757
29           Laptop Cooling Pad         260      0.069341
30                Action Camera         200     -0.425953
31               Smart Doorbell         180     -0.591051
32              Streaming Stick         430      1.472674
33           Portable Projector         120     -1.086345
34                 Gaming Chair          90     -1.333992
35               Desk Organizer         160     -0.756149
36              USB Flash Drive         320      0.564635
37       Phone Screen Protector         380      1.059929
38                Laptop Sleeve         210     -0.343404
39           Wireless Presenter         130     -1.003796
40         Tablet Keyboard Case         150     -0.838698
41             Smart Thermostat         110     -1.168894
42              Security Camera         260      0.069341
43                 Drone Camera          70     -1.499090
44              Electric Kettle         310      0.482086
45                    Air Fryer         200     -0.425953
46                 Robot Vacuum         120     -1.086345
47                  Smart Scale         170     -0.673600
48          Digital Photo Frame         150     -0.838698
49                 Portable Fan         240     -0.095757

In [ ]:
df['Price_Decimal']=df['Price']/100000
print("\nDecimal Scaled Price:")
print(df[['Product_Name','Price','Price_Decimal']])

Decimal Scaled Price:
                   Product_Name  Price  Price_Decimal
0                Wireless Mouse    799        0.00799
1             Bluetooth Speaker   1499        0.01499
2                  USB Keyboard    699        0.00699
3                Gaming Headset   2499        0.02499
4                    Smartwatch   3999        0.03999
5                    Power Bank   1199        0.01199
6                  Laptop Stand    899        0.00899
7                        Webcam   1899        0.01899
8                  Portable SSD   5499        0.05499
9              Wireless Charger    999        0.00999
10  Noise Cancelling Headphones   7999        0.07999
11          Mechanical Keyboard   4599        0.04599
12                 Gaming Mouse   1599        0.01599
13                 Tablet Stand    699        0.00699
14                      USB Hub    899        0.00899
15          External Hard Drive   6499        0.06499
16            Smartphone Tripod   1199        0.01199
17              Laptop Backpack   1999        0.01999
18            Bluetooth Earbuds   2999        0.02999
19                LED Desk Lamp   1299        0.01299
20                 Phone Holder    499        0.00499
21            Wireless Keyboard   2499        0.02499
22             Portable Monitor   8999        0.08999
23                   Smart Plug    799        0.00799
24                  WiFi Router   3499        0.03499
25              Graphics Tablet   4599        0.04599
26                   VR Headset  12999        0.12999
27                   Microphone   2199        0.02199
28             Smart Light Bulb    699        0.00699
29           Laptop Cooling Pad   1499        0.01499
30                Action Camera   9999        0.09999
31               Smart Doorbell   5999        0.05999
32              Streaming Stick   3499        0.03499
33           Portable Projector  11999        0.11999
34                 Gaming Chair  15999        0.15999
35               Desk Organizer    599        0.00599
36              USB Flash Drive    799        0.00799
37       Phone Screen Protector    299        0.00299
38                Laptop Sleeve    999        0.00999
39           Wireless Presenter   1499        0.01499
40         Tablet Keyboard Case   2999        0.02999
41             Smart Thermostat  10999        0.10999
42              Security Camera   4999        0.04999
43                 Drone Camera  24999        0.24999
44              Electric Kettle   1999        0.01999
45                    Air Fryer   7999        0.07999
46                 Robot Vacuum  18999        0.18999
47                  Smart Scale   2499        0.02499
48          Digital Photo Frame   3499        0.03499
49                 Portable Fan    999        0.00999

Part-B

In [ ]:
#DataSet
import pandas as pd
import numpy as np
data={
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Male','Female','Male','Female'],
    'Payment_Method':['UPI','Credit Card','UPI','Cash on Delivery','UPI','Credit Card'],
    'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
    'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
    'Order_Value':[4000,2300,3200,5200,1000,4300]
}
df=pd.DataFrame(data)
print("Original Data:")
print(df)

Original Data:
   Order_ID Customer_Gender    Payment_Method Product_Category       City  \
0       101            Male               UPI      Electronics       Pune
1       102          Female       Credit Card         Clothing     Mumbai
2       103            Male               UPI             Home      Delhi
3       104          Female  Cash on Delivery      Electronics  Bangalore
4       105            Male               UPI           Beauty       Pune
5       106          Female       Credit Card      Electronics  Hyderabad

   Order_Value
0         4000
1         2300
2         3200
3         5200
4         1000
5         4300

In [ ]:
#method 1 Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender_Label']=le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,PAyment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4000,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Male,UPI,Home,Delhi,3200,1
3,104,Female,Cash on Delivery,Electronics,Bangalore,5200,0
4,105,Male,UPI,Beauty,Pune,1000,1
5,106,Female,Credit Card,Electronics,Hyderabad,4300,0

In [ ]:
#method 2 one hot coding
df_encoded=pd.get_dummies(df,columns=['Payment_Method'])
df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Payment_Method_Cash on Delivery,Payment_Method_Credit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4000,False,False,True
1,102,Female,Clothing,Mumbai,2300,False,True,False
2,103,Male,Home,Delhi,3200,False,False,True
3,104,Female,Electronics,Bangalore,5200,True,False,False
4,105,Male,Beauty,Pune,1000,False,False,True
5,106,Female,Electronics,Hyderabad,4300,False,True,False

In [ ]:
#Method3 Encoded multiple columns
df_multi=pd.get_dummies(df,columns=['Product_Category','City'])
df_multi

,Order_ID,Customer_Gender,Payment_Method,Order_Value,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,4000,False,False,True,False,False,False,False,False,True
1,102,Female,Credit Card,2300,False,True,False,False,False,False,False,True,False
2,103,Male,UPI,3200,False,False,False,True,False,True,False,False,False
3,104,Female,Cash on Delivery,5200,False,False,True,False,True,False,False,False,False
4,105,Male,UPI,1000,True,False,False,False,False,False,False,False,True
5,106,Female,Credit Card,4300,False,False,True,False,False,False,True,False,False

In [ ]:
#Method Dummy Encoding(Drop First)
df_dummy=pd.get_dummies(df,columns=['Payment_Method'],drop_first=True)
df_dummy

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Payment_Method_Credit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4000,False,True
1,102,Female,Clothing,Mumbai,2300,True,False
2,103,Male,Home,Delhi,3200,False,True
3,104,Female,Electronics,Bangalore,5200,False,False
4,105,Male,Beauty,Pune,1000,False,True
5,106,Female,Electronics,Hyderabad,4300,True,False

In [ ]:
#new Data Set
import pandas as pd
df=pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['PS']=le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,PS
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [ ]:
df_encoded=pd.get_dummies(df,columns=['Number_of_Backlogs'])
df_encoded

,Roll_No,Gender,Department,CGPA,Attendance_Percentage,Placement_Status,Salary,PS,Number_of_Backlogs_0,Number_of_Backlogs_1,Number_of_Backlogs_2,Number_of_Backlogs_3
0,101,Female,Computer,8.2,92,Placed,450000,1,True,False,False,False
1,102,Male,IT,7.5,85,Not Placed,0,0,False,True,False,False
2,103,Female,ENTC,9.1,96,Placed,550000,1,True,False,False,False
3,104,Male,Mechanical,6.8,78,Not Placed,0,0,False,False,True,False
4,105,Female,Computer,8.7,88,Placed,480000,1,True,False,False,False
5,106,Male,Civil,7.2,72,Not Placed,0,0,False,False,False,True
6,107,Female,IT,8.9,91,Placed,500000,1,True,False,False,False
7,108,Male,Computer,6.5,80,Not Placed,0,0,False,True,False,False
8,109,Female,ENTC,7.8,84,Placed,420000,1,True,False,False,False
9,110,Male,Mechanical,7.0,76,Not Placed,0,0,False,False,True,False

In [ ]:
df_multi=pd.get_dummies(df,columns=['Gender','Placement_Status'])
df_multi

,Roll_No,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Salary,PS,Gender_Female,Gender_Male,Placement_Status_Not Placed,Placement_Status_Placed
0,101,Computer,8.2,0,92,450000,1,True,False,False,True
1,102,IT,7.5,1,85,0,0,False,True,True,False
2,103,ENTC,9.1,0,96,550000,1,True,False,False,True
3,104,Mechanical,6.8,2,78,0,0,False,True,True,False
4,105,Computer,8.7,0,88,480000,1,True,False,False,True
5,106,Civil,7.2,3,72,0,0,False,True,True,False
6,107,IT,8.9,0,91,500000,1,True,False,False,True
7,108,Computer,6.5,1,80,0,0,False,True,True,False
8,109,ENTC,7.8,0,84,420000,1,True,False,False,True
9,110,Mechanical,7.0,2,76,0,0,False,True,True,False